# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: s3-sync

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Remove from S3
      run: aws s3 rm s3://thielking.dev/ --recursive
    - name: Upload to S3
      run: aws s3 sync . s3://thielking.dev/ --exclude ./terraform --exclude .gitignore
    - name: Invalidate Cloudfront
      run: aws cloudfront create-invalidation --distribution-id E3559DNRZYRSBA -paths "/*"
